image: maven:latest

services:
  - name: docker:dind

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_DRIVER: "overlay2"

stages:
  - build
  - test

cache:
  paths:
    - .m2/repository

build:
  stage: build
  script:
    - mvn clean package
  only:
    - merge_requests
    - /^dev/

test:
  stage: test
  script:
    - mvn test
  only:
    - merge_requests
    - /^dev/
