openapi: 3.0.2
info:
  title: Abstraction
  description: Abstraction App
  version: '1.0'
servers:
  - url: http://localhost:8080/abstraction/api

tags:
  - name: Decoding
    description: Decoding info

paths:
  /decode:
    post:
      tags:
        - Decoding
      summary: Decode file
      operationId: decodeFile
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
      responses:
        200:
          description: OK