openapi: 3.0.2
info:
  title: Летняя Практика
  description: Сервис для души
  version: '1.0'
servers:
  - url: http://localhost:8080

tags:
  - name: QuotationController
    description: Возвращает гифку

paths:
  /quotation:
    get:
      tags:
        - Quotation
      summary: Realize Quotation
      operationId: quotation
      responses:
        200:
          description: OK
          content:
            text/plain:
              schema:
                type: string
